name:                Poker
version:             0.1.1
github:              scottcmarks/Poker
license:
author:              Scott Marks
maintainer:          scott@magnolia-heights.com
copyright:           Magnolia Heights R&D

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
synopsis:            Poker -- accessing and updating poker play results
# category:            Web
category:            Entertainment

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/scottcmarks/Poker#readme>

dependencies:
- base >= 4.10 && < 10
- rio >= 0.1.1.0
- List
- bytestring
- conduit
- containers
- data-ordlist
- fmt
- haskeline
- lens
- monad-logger
- optparse-applicative
- optparse-simple
- parsec
- persistent
- persistent-sqlite
- persistent-template
- profunctors
- resourcet
- string-qq
- text
- time
- transformers
- sqlite-simple
- unix-time
- unliftio-core


ghc-options:
- -Wall
- -Wcompat
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wredundant-constraints
- -optP-Wno-nonportable-include-path # workaround [Filename case on macOS · Issue #4739 · haskell/cabal](https://github.com/haskell/cabal/issues/4739)

library:
  source-dirs: src

executables:
  poker:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - Poker

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  poker-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - Poker
    - hspec

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
